## Numpy学习
>numpy可以用于：
* 数组和逻辑运算
* 傅立叶变换和图形操作
* 线性代数相关操作

通常和Scipy、Matplotlib一起使用，是matlab良好的替代，由于开源，所以有额外的优势

[学习来源](https://docs.scipy.org/doc/numpy/user/quickstart.html)

# basic

## Ndarray对象
>Ndarray对象-N维数组类型，是相同类型元素的集合，从索引0开始访问。

dtype-数据类型对象；Ndarray-每个元素是dtype的对象

## numpy基础
* 在numpy中，dimensions 称为  axes.
>**个人理解，dimensions应该是外面`[]`的层数，有几个`[]`就是几维**

`[1, 2, 1] `，这个是1个维度，one axis

`[[ 1., 0., 0.],
 [ 0., 1., 2.]]`，这个是2个维度，two axes，The first axis has a length of 2, the second axis has a length of 3.所以第一维代表数组的个数，第二维表示每个数组的长度。

In [1]:
import numpy as np
from numpy import *

In [31]:
pi

3.141592653589793

In [33]:
dt = np.array([ [ [ 1., 0., 0.],
                    [ 0., 1., 2.],
                    [ 3., 4., 5.],
                    [1.,4.,6.] ] ])

### ndarray.ndim
* the number of **`axes (dimensions)`** of the array.(数组轴的数量)

dt因为有3个`[]`

In [35]:
dt.ndim

3

## ndarray.shape
* size of the array in each dimension
(每一个维度的大小)
>对于矩阵(n,m)，shape的长度，就是aexs，或者dt.ndim；因为`[]`有3层，长度为3

In [37]:
dt.shape

(1, 4, 3)

## ndarray.size
* the total number of elements of the array. 
(数组元素总和)

In [38]:
dt.size

12

### ndarray.dtype
* an object describing the type of the elements in the array.(描述元素类型的对象)

[numpy数据类型](https://docs.scipy.org/doc/numpy/user/basics.types.html)

In [47]:
dt.dtype.name

'float64'

### ndarray.itemsize
* the size in bytes of each element of the array.(每个元素的字节大小)
>dt中每个元素，字节大小为8

In [40]:
dt.itemsize

8

# Array Creation
1.  a regular Python list or tuple using the `array` function
>1. 由`array`函数创建数组，数据类型，根据元素序列决定；
c 是在数组中定义了`dtype`数据类型

因为序列中都是`int`类型

In [50]:
dt = np.array([1, 3, 5])

In [51]:
dt.dtype

dtype('int64')

In [52]:
c = np.array( [ [1,2], [3,4] ], dtype=complex)

In [53]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

2. the elements of an array are originally unknown, but its size is known. (数组具体元素未知，但大小知道)
>* `zero`,`ones`; 
>* **`empty`:whose initial content is random and depends on the state of the memory. **(根据当前内存状态创建随机数组)

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.empty((5,3))

array([[-2.68156159e+154, -2.68156159e+154,  5.92878775e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

3. To create sequences of numbers(用`range`函数制造数组)

>* `arange`:不包括结尾的数字
* `linspace`:可以通过属性，设置末尾数字

In [66]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [67]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.linspace(0,10,10,dtype='int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

# Printing Arrays
>* 从左到右，从上到下打印
* 如果数组太大，会省略中间部分

To disable this behaviour and force NumPy to print the entire array, you can change the printing options using `set_printoptions.`

打印整个数组，需要用`set_printoption`

In [72]:
c = np.arange(24).reshape(2,3,4)

In [73]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [2]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [79]:
np.set_printoptions()

# Basic Operations
* 基本的加减乘除，`**`是乘方，可以进行布尔运算

In [2]:
b = np.arange( 6 )

In [3]:
b

array([0, 1, 2, 3, 4, 5])

In [4]:
b**2

array([ 0,  1,  4,  9, 16, 25])

In [5]:
b>2

array([False, False, False,  True,  True,  True])

>* 矩阵乘法，numpy中使用`@`或者`dot`；
* 矩阵或者数组对应位置元素相乘，用`*`

In [6]:
A = np.array([[0,1],[3,2]])

In [7]:
A

array([[0, 1],
       [3, 2]])

In [8]:
B = np.arange(4).reshape(2,2)

In [9]:
B

array([[0, 1],
       [2, 3]])

In [22]:
A@B

array([[2, 3],
       [4, 9]])

In [23]:
A.dot(B)

array([[2, 3],
       [4, 9]])

In [24]:
A*B

array([[0, 1],
       [6, 6]])

* When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one

当对数组操作工程中，由于数据类型不同，结果由更精确的类型决定
>比如下面，b是float64,d是complex128,两者的运算结果dtype是complex128

In [33]:
b = np.linspace(0,pi,3)
d = np.exp(b*1j)

In [36]:
b.dtype.name

'float64'

In [37]:
d.dtype.name

'complex128'

>**ndarray对象的`方法`可以tab后自己查看涉及的功能很多，需要用到再去检索即可**

* by specifying the axis parameter you can apply an operation along the specified axis of an array

* 数组中`axis`参数，可以用于具体轴的操作
>b，3维就不清楚这个轴怎么计算的了？待补充--3d数组的三维分别是第一块、第二块、纵向第三块

b中，第一块是按`行`操作；第二块按`数组块`操作；第三块按`连接两块矩阵的列操作`

In [10]:
b = np.arange(12).reshape(2,3,2)

In [11]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [16]:
b.mean()

5.5

In [177]:
b.sum(axis=1)

array([[ 6,  9],
       [24, 27]])

# Universal Functions
numpy存在一些通用的函数，可以调用，比如：exp，sqrt等等具体可以查官网

# Indexing, Slicing and Iterating
一维数组，索引、切片和迭代同python的list


In [70]:
a = np.arange(10)**3

In [71]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [72]:
a[2]

8

In [73]:
a[2:5]

array([ 8, 27, 64])

In [75]:
a[:6:2] = -1000

>把数组，索引0-6按步长2开始索引，并将值替换成-1000

In [76]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

>黑科技，list列表可以按步长(索引)来切片;**对于字符串切分，可以将字符串放入列表,或者用列表表达式**

对于`array[::-1]反转数组`;迭代可以同list一样的操作

In [131]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [133]:
[x**(1/3) for x in a]

/Users/tony/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


[nan,
 1.0,
 nan,
 3.0,
 nan,
 4.999999999999999,
 5.999999999999999,
 6.999999999999999,
 7.999999999999999,
 8.999999999999998]

>Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas

多维数组，每个axis都有一个index，之间用，隔开

>__`np.fromfunction(function,shape,*kwargs)`__这个函数，按funcntion来生成数组。

对于2维数组b而言，索引b[2,3]就是2行3列位置的元素;b[:,2]就是所有行的index=2的列

In [25]:
b = np.fromfunction(lambda i,j:i*j,(6,4),dtype=int)

In [150]:
b

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12],
       [ 0,  5, 10, 15]])

In [151]:
b[2,3]

6

In [158]:
b[:,2]

array([ 0,  2,  4,  6,  8, 10])

![](https://ws1.sinaimg.cn/large/006tNbRwly1fygphl4j3ej31hc08eq49.jpg)
当数组有非常多的维度，可以用`...`来代替每次的`:`

In [26]:
k = np.arange(24).reshape(2,4,3)

In [27]:
k

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [7]:
k.shape

(2, 4, 3)

In [8]:
k[0,...]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
k[...,0]

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21]])

* if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array

对数组每个元素进行操作，可以用`flat`属性，ndarray.flat是一个迭代器，遍历数组每个元素。

In [35]:
[i for i in k.flat]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

# Shape Manipulation
**1. Changing the shape of an array**

    数组塑形：
    * ravel、reshape、T,都可以塑形，但是不改变原数组
    * resize,改变数组本身

In [15]:
a = np.floor(10*np.random.random((3,4)))

In [16]:
a

array([[4., 9., 6., 2.],
       [3., 7., 1., 5.],
       [5., 1., 5., 5.]])

In [17]:
a.shape

(3, 4)

In [18]:
a.ravel()      #平铺数组

array([4., 9., 6., 2., 3., 7., 1., 5., 5., 1., 5., 5.])

In [19]:
a.reshape(6,2)      #改变形状

array([[4., 9.],
       [6., 2.],
       [3., 7.],
       [1., 5.],
       [5., 1.],
       [5., 5.]])

In [20]:
a.T             #转置

array([[4., 3., 5.],
       [9., 7., 1.],
       [6., 1., 5.],
       [2., 5., 5.]])

In [23]:
a.resize((2,6))           #改变数组本身，不返回任何值

In [22]:
a

array([[4., 9., 6., 2., 3., 7.],
       [1., 5., 5., 1., 5., 5.]])

>If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

>如果数组有一个维度赋值为-1，则根据其他维度来自动计算；
* 比如a.shape = (2,6),要将a改变成3行的数组，但是列数不知道，可以设置为-1，让其自动计算

In [24]:
a.reshape(3,-1)             #example 1

array([[4., 9., 6., 2.],
       [3., 7., 1., 5.],
       [5., 1., 5., 5.]])

In [28]:
a.reshape(6,-1)           #example  2

array([[4., 9.],
       [6., 2.],
       [3., 7.],
       [1., 5.],
       [5., 1.],
       [5., 5.]])

2. **Stacking together different arrays**
    * 用`vstack`,`hstack`,将两个数组，纵向或者横向拼接，传入参数是-->元组
    * `column_stack`,把一维数组，按列存储组成2维

In [29]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [50]:
a

array([[3., 8.],
       [1., 8.]])

In [31]:
b

array([[6., 6.],
       [7., 9.]])

In [32]:
np.vstack((a,b))         #纵向拼接

array([[3., 8.],
       [1., 8.],
       [6., 6.],
       [7., 9.]])

In [34]:
np.hstack((a,b))        #横向拼接

array([[3., 8., 6., 6.],
       [1., 8., 7., 9.]])

In [35]:
np.column_stack((a,b))        #作用同hstack;

array([[3., 8., 6., 6.],
       [1., 8., 7., 9.]])

In [37]:
d1 = np.array((1,2,3))
d2 = np.array((2,3,4))

In [41]:
np.column_stack((d1,d2))        #按列存储

array([[1, 2],
       [2, 3],
       [3, 4]])

In [42]:
np.hstack((d1,d2))               #hstack和column不同

array([1, 2, 3, 2, 3, 4])

>**此处`hstack`和`column_stack`区别:**？？存疑，待有机会解决

In [53]:
print([1,2,3,4])

[1, 2, 3, 4]


* In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (“:”)

用`r_ and c_ `通过堆叠数字沿axis来创建数组

In [55]:
np.r_[1:4,9,10,13]

array([ 1,  2,  3,  9, 10, 13])

**3. Splitting one array into several smaller ones**
>切分数组，成小部分:
* hsplit-->水平
* vsplit-->垂直
* split-->自定义
>Split an array into multiple sub-arrays.
>>**split:**用法，传入一个数组，第二参数是一个索引或者一个切片；1.参数2是数组或者切片则按照axis来划分；2.如果索引超出维度，会返回一个空子数组
* If indices_or_sections is a 1-D array of sorted integers, **the entries indicate where along axis the array is split.**
* If an index exceeds the dimension of the array along axis, **an empty sub-array is returned correspondingly.**


In [56]:
a = np.floor(10*np.random.random((2,12)))

In [57]:
a

array([[2., 7., 1., 8., 7., 6., 4., 6., 1., 4., 1., 3.],
       [3., 5., 5., 6., 4., 1., 0., 9., 2., 4., 0., 5.]])

In [71]:
print(np.hsplit(a,3))        #把数组切分成3个部分，返回一个列表，数有几个array即可

[array([[2., 7., 1., 8.],
       [3., 5., 5., 6.]]), array([[7., 6., 4., 6.],
       [4., 1., 0., 9.]]), array([[1., 4., 1., 3.],
       [2., 4., 0., 5.]])]


In [78]:
np.hsplit(a,(2,3))         #是按列的索引值进行切分，2，3就是指从左到右索引2，3为分割点。

[array([[2., 7.],
        [3., 5.]]), array([[1.],
        [5.]]), array([[8., 7., 6., 4., 6., 1., 4., 1., 3.],
        [6., 4., 1., 0., 9., 2., 4., 0., 5.]])]

# Copies and Views
* No Copy at All
* View or Shallow Copy-->view()
* Deep Copy--->copy()

In [38]:
k1 = k.view()

In [39]:
k1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# Functions and Methods Overview
>Array Creation

>Conversions

>Manipulations

>Questions

>Ordering

>Operations

>Basic Statistics

>Basic Linear Algebra


# Broadcasting
* 当两个数组的形状并不相同的时候，我们可以通过扩展数组的方法来实现相加、相减、相乘等操作，这种机制叫做广播
>2个核心：
    * 维度不同，末尾轴长度相同
    * 维度相同，有一个轴为1

![](https://ws4.sinaimg.cn/large/006tNbRwly1fyhtygz6qjj313q0iwdoh.jpg)
![](https://ws2.sinaimg.cn/large/006tNbRwly1fyhtygpitgj310e0l8n74.jpg)
![](https://ws3.sinaimg.cn/large/006tNbRwly1fyhwhzuk4fj31580jcdoh.jpg)